{
	{
		Groups = {
			"LegionSquad",
			"KillStogie",
		},
		handle = 1027822108,
		items = {},
		map = "ds3oUXy",
		name = "UnitMarker#108 (LegionSquad, KillStogie)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"MERCSquad",
		},
		handle = 1057428817,
		items = {
			{
				editor_view_abridged = "Start conversation.",
				filter_type = "conversation",
				reference_id = "HireNumb",
				type = "UnitStartConversation",
			},
		},
		map = "ds3oUXy",
		name = "UnitMarker#817 (MERCSquad)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
			"KillCougar",
		},
		handle = 1078898326,
		items = {},
		map = "ds3oUXy",
		name = "UnitMarker#326 (LegionSquad, KillCougar)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
		},
		handle = 1150006183,
		items = {},
		map = "ds3oUXy",
		name = "UnitMarker#183 (LegionSquad)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"MERCSquad",
		},
		handle = 1166115490,
		items = {
			{
				editor_view_abridged = "Start conversation.",
				filter_type = "conversation",
				reference_id = "HireCougar",
				type = "UnitStartConversation",
			},
		},
		map = "ds3oUXy",
		name = "UnitMarker#490 (MERCSquad)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
			"KillNumb",
		},
		handle = 1216939318,
		items = {},
		map = "ds3oUXy",
		name = "UnitMarker#318 (LegionSquad, KillNumb)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
		},
		handle = 1292132926,
		items = {},
		map = "ds3oUXy",
		name = "UnitMarker#926 (LegionSquad)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
		},
		handle = 1299036243,
		items = {},
		map = "ds3oUXy",
		name = "UnitMarker#243 (LegionSquad)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
			"KillCougar",
		},
		handle = 1412117960,
		items = {},
		map = "ds3oUXy",
		name = "UnitMarker#960 (LegionSquad, KillCougar)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
			"KillGaston",
		},
		handle = 1430939453,
		items = {},
		map = "ds3oUXy",
		name = "UnitMarker#453 (LegionSquad, KillGaston)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"MERCSquad",
		},
		handle = 1436832369,
		items = {
			{
				editor_view_abridged = "Start conversation.",
				filter_type = "conversation",
				reference_id = "HireStogie",
				type = "UnitStartConversation",
			},
		},
		map = "ds3oUXy",
		name = "UnitMarker#369 (MERCSquad)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
		},
		handle = 1461933538,
		items = {},
		map = "ds3oUXy",
		name = "UnitMarker#538 (LegionSquad)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
			"KillStogie",
		},
		handle = 1465508640,
		items = {},
		map = "ds3oUXy",
		name = "UnitMarker#640 (LegionSquad, KillStogie)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
			"KillStogie",
		},
		handle = 1506504536,
		items = {},
		map = "ds3oUXy",
		name = "UnitMarker#536 (LegionSquad, KillStogie)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
			"KillNumb",
		},
		handle = 1599502950,
		items = {},
		map = "ds3oUXy",
		name = "UnitMarker#950 (LegionSquad, KillNumb)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"MERCSquad",
		},
		handle = 1627266630,
		items = {
			{
				editor_view_abridged = "Start conversation.",
				filter_type = "conversation",
				reference_id = "HireGaston",
				type = "UnitStartConversation",
			},
		},
		map = "ds3oUXy",
		name = "UnitMarker#630 (MERCSquad)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
			"KillStogie",
		},
		handle = 1781220721,
		items = {},
		map = "ds3oUXy",
		name = "UnitMarker#721 (LegionSquad, KillStogie)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
		},
		handle = 1818862998,
		items = {},
		map = "ds3oUXy",
		name = "UnitMarker#998 (LegionSquad)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
			"KillGaston",
		},
		handle = 1861289122,
		items = {},
		map = "ds3oUXy",
		name = "UnitMarker#122 (LegionSquad, KillGaston)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}